/* eslint-disable */
// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request
        ? input.headers
        : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) =>
        headers.set(key, value),
      );
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn(
      "[Supabase] Missing Supabase environment variables. Falling back to an interactive localStorage mock database.",
    );
    return mockSupabaseClient as any;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

import { get60SeedData } from "../../data/seedData";

// Define storage keys for mock database
const STORAGE_KEYS = {
  companies: "mock_sb_companies",
  employees: "mock_sb_employees",
  diagnostics: "mock_sb_diagnostics",
  roles_config: "mock_sb_roles_config",
  user_role_assignments: "mock_sb_user_role_assignments",
};

// Initialize default mock data if localStorage is empty
if (typeof window !== "undefined") {
  try {
    if (!localStorage.getItem(STORAGE_KEYS.companies)) {
      localStorage.setItem(
        STORAGE_KEYS.companies,
        JSON.stringify([
          {
            id: "company-default-id",
            name: "HumanAI First Company",
            created_at: new Date().toISOString(),
          },
        ]),
      );
    }
    const currentEmployees = JSON.parse(
      localStorage.getItem(STORAGE_KEYS.employees) || "[]",
    );
    if (
      !localStorage.getItem(STORAGE_KEYS.employees) ||
      currentEmployees.length !== 35
    ) {
      const seed = get60SeedData("company-default-id");
      localStorage.setItem(
        STORAGE_KEYS.employees,
        JSON.stringify(seed.employees),
      );
      localStorage.setItem(
        STORAGE_KEYS.diagnostics,
        JSON.stringify(seed.diagnostics),
      );
    }
  } catch (e) {
    console.warn("Storage is not accessible", e);
  }
}

// Mock query builder
class MockQueryBuilder {
  private tableName: string;
  private filters: Array<(item: any) => boolean> = [];
  private sortFn: ((a: any, b: any) => number) | null = null;
  private limitCount: number | null = null;
  private operation: "select" | "insert" | "update" | "delete" | "upsert" =
    "select";
  private payload: any = null;

  constructor(tableName: string) {
    this.tableName = tableName;
  }

  select(fields?: string) {
    this.operation = "select";
    return this;
  }

  eq(column: string, value: any) {
    this.filters.push((item) => item[column] === value);
    return this;
  }

  neq(column: string, value: any) {
    this.filters.push((item) => item[column] !== value);
    return this;
  }

  not(column: string, operator: string, value: any) {
    if (operator === "is" && value === null) {
      this.filters.push(
        (item) => item[column] !== null && item[column] !== undefined,
      );
    } else {
      this.filters.push((item) => item[column] !== value);
    }
    return this;
  }

  order(column: string, options?: { ascending?: boolean }) {
    const asc = options?.ascending !== false;
    this.sortFn = (a, b) => {
      const valA = a[column];
      const valB = b[column];
      if (valA === valB) return 0;
      if (valA == null) return asc ? -1 : 1;
      if (valB == null) return asc ? 1 : -1;
      return asc ? (valA < valB ? -1 : 1) : valA > valB ? -1 : 1;
    };
    return this;
  }

  limit(n: number) {
    this.limitCount = n;
    return this;
  }

  insert(rows: any) {
    this.operation = "insert";
    this.payload = rows;
    return this;
  }

  upsert(rows: any) {
    this.operation = "upsert";
    this.payload = rows;
    return this;
  }

  update(fields: any) {
    this.operation = "update";
    this.payload = fields;
    return this;
  }

  delete() {
    this.operation = "delete";
    return this;
  }

  private getData() {
    const key = (STORAGE_KEYS as any)[this.tableName];
    if (!key) return [];
    try {
      return JSON.parse(localStorage.getItem(key) || "[]");
    } catch {
      return [];
    }
  }

  private saveData(data: any[]) {
    const key = (STORAGE_KEYS as any)[this.tableName];
    if (key) {
      localStorage.setItem(key, JSON.stringify(data));
    }
  }

  private execute() {
    let list = this.getData();

    // Expand diagnostics -> employee
    if (this.tableName === "diagnostics") {
      const employees = JSON.parse(
        localStorage.getItem(STORAGE_KEYS.employees) || "[]",
      );
      list = list.map((diag: any) => {
        const emp = employees.find((e: any) => e.id === diag.employee_id);
        return {
          ...diag,
          employee: emp || null,
        };
      });
    }

    if (this.operation === "select") {
      for (const filter of this.filters) {
        list = list.filter(filter);
      }
      if (this.sortFn) {
        list.sort(this.sortFn);
      }
      if (this.limitCount !== null) {
        list = list.slice(0, this.limitCount);
      }
      return { data: list, error: null };
    }

    if (this.operation === "insert") {
      const rows = Array.isArray(this.payload) ? this.payload : [this.payload];
      const newRows = rows.map((row) => ({
        id: Math.random().toString(36).substring(2, 11),
        created_at: new Date().toISOString(),
        ...row,
      }));
      const updatedList = [...list, ...newRows];
      this.saveData(updatedList);
      return {
        data: Array.isArray(this.payload) ? newRows : newRows[0],
        error: null,
      };
    }

    if (this.operation === "upsert") {
      const rows = Array.isArray(this.payload) ? this.payload : [this.payload];
      const currentList = [...list];
      for (const row of rows) {
        const key = this.tableName === "user_role_assignments" ? "email" : "id";
        const index = currentList.findIndex(
          (item: any) => item[key] === row[key],
        );
        const updatedRow = {
          updated_at: new Date().toISOString(),
          ...row,
        };
        if (index >= 0) {
          currentList[index] = { ...currentList[index], ...updatedRow };
        } else {
          currentList.push(updatedRow);
        }
      }
      this.saveData(currentList);
      return {
        data: Array.isArray(this.payload) ? rows : rows[0],
        error: null,
      };
    }

    if (this.operation === "update") {
      const updatedList = list.map((item) => {
        let match = true;
        for (const filter of this.filters) {
          if (!filter(item)) {
            match = false;
            break;
          }
        }
        if (match) {
          return { ...item, ...this.payload };
        }
        return item;
      });
      this.saveData(updatedList);
      return { data: updatedList, error: null };
    }

    if (this.operation === "delete") {
      const remainingList = list.filter((item) => {
        let match = true;
        for (const filter of this.filters) {
          if (!filter(item)) {
            match = false;
            break;
          }
        }
        return !match;
      });
      this.saveData(remainingList);
      return { data: null, error: null };
    }

    return { data: null, error: null };
  }

  then(onfulfilled?: (value: any) => any, onrejected?: (reason: any) => any) {
    const res = this.execute();
    return Promise.resolve(res).then(onfulfilled, onrejected);
  }

  single() {
    const self = this;
    return {
      then(
        onfulfilled?: (value: any) => any,
        onrejected?: (reason: any) => any,
      ) {
        const { data, error } = self.execute();
        const singleData = Array.isArray(data) ? data[0] || null : data;
        return Promise.resolve({ data: singleData, error }).then(
          onfulfilled,
          onrejected,
        );
      },
    };
  }

  maybeSingle() {
    return this.single();
  }
}

// Mock Supabase Client
const mockSupabaseClient = {
  from(tableName: string) {
    return new MockQueryBuilder(tableName);
  },
  auth: {
    getSession: () => Promise.resolve({ data: { session: null }, error: null }),
    onAuthStateChange: () => ({
      data: { subscription: { unsubscribe: () => {} } },
    }),
  },
};

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy(
  {} as ReturnType<typeof createSupabaseClient>,
  {
    get(_, prop, receiver) {
      if (!_supabase) _supabase = createSupabaseClient();
      return Reflect.get(_supabase, prop, receiver);
    },
  },
);
